### ISSUE TITLE
What kind of color scheme is used in the screenshot?

### ISSUE THREAD

**Issue by rfegq4** [lucy/tewi-font#10]
What kind of color scheme is used in the screenshot?

https://camo.githubusercontent.com/f27cba2c2909c25902747d3c8252c1eb937ee5bb/68747470733a2f2f7075752e73682f61763337692f356431353264373637362e706e67

**Comment by lucy** [comment]
https://github.com/lucy/.-/commit/1b93ea54a3aa26f4329ff72c09e606ae73948d9d

**Comment by wowse** [comment]
>lucy/.-@1b93ea5

hey, that link is 404. i was searching for that color scheme too.

**Comment by lucy** [comment]
I no longer have it.
