### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by sshbio** [lucy/tewi-font#18]
I thought this font would be too small, but it is readable by its design, and I the more I use it, the more I like the choices made.
Perfectly aligned semigraphic characters, large dots, verify wide coverage... I love this font!

I enjoy making fonts ([miniwi](https://github.com/sshbio/miniwi)), and I may have some time to contribute some day.  Some hints about the software or workflow you use?

[EDIT]: Ugly typos

**Comment by lucy** [comment]
I draw glyphs in gbdfed, and look at wikipedia's list of unicode characters, official unicode charts and several other fonts for reference.

Note that I don't really trust other people to draw glyphs how I want them. :)

**Comment by sshbio** [comment]
Thank you for these tips!

I sure understand that you want your font to only include characters you like.  :)

What I had in mind was extending the character set to be able to render [this](https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt), but I never encountered a character that tewi-font could not render in real use (code, French, terminal interfaces) but CJK of course.  Font fallback may be a better option for the rare languages or those with many glyphs.

What I can do is generating a `.psf` version as described in #7.

I will try to fit in either 128 or 256 characters slots:

1. **ASCII**

2. **Language support**:

  - Most common diacritics
  - Cyrillic
  - Greek
  - Hebrew

3. **Semigraphics**:

  - [Box drawing](https://en.wikipedia.org/wiki/Box-drawing_character)
  - [Blocks and gradients](https://en.wikipedia.org/wiki/Block_Elements)
  - *Not braille: the 256 braille characters would fill all the available slots*

4. **Symbols, featuring**:

  - Math symbols
  - Icons-like characters
  - Pretty punctuation
  - Localized symbols like currencies

To save slots and support more characters, I will try to use [equivalents](https://github.com/sshbio/miniwi/blob/master/bdf2psf/standard.equivalents).

**Comment by lucy** [comment]
That would be very nice. :)

**Comment by lucy** [comment]
I'll attempt to cover most of the non-alphabet glyphs on https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt eventually.

**Comment by sshbio** [comment]
Wow, I see the commits counter rolling with new glyphs, thanks for this work.  I'm just getting started.
