### ISSUE TITLE
Hyphen and Minus symbol show up identically.

### ISSUE THREAD

**Issue by samcv** [lucy/tewi-font#27]
Compare:
```
-10 # normal hyphen (U+002D)

−10 # Minus U+2212
```

`-−` You can see one is generally narrower and vertically at a different position.

Would really like to be able to tell them apart. Thanks!

**Comment by samcv** [comment]
Thank you, works for tewihm, will you add it to the other fonts as well (I prefer tewi2a). I will use tewihm for now. :)

**Comment by lucy** [comment]
See #29. It'll be sort of annoying to do properly so it might take a while.

**Comment by samcv** [comment]
Okay thanks 😄
