### ISSUE TITLE
Python 3 in shebang

### ISSUE THREAD

**Issue by s-gilles** [lucy/tewi-font#31]
Since 2.0.1, python3 is required (and is mentioned in the README by the next commit), but the shebang in scripts/merge.py could be a bit more clear.  On my system, for example, `python` happens to be python2, so `make` fails, but specifying `#!/usr/bin/env python3` in merge.py fixes this.

**Comment by funeralismatic** [comment]
@lucy 

>but specifying `#!/usr/bin/env python3` in merge.py fixes this

>change `script` shebangs to `python2`

What?

```
python2 is not supported by python3.5
python2 is not supported by python3.5
make: *** [Makefile:22: tewi2a-medium-11.bdf] Error 127
make: *** Waiting for unfinished jobs....
make: *** [Makefile:22: tewihm-medium-11.bdf] Error 127
python2 is not supported by python3.5
python2 is not supported by python3.5
make: *** [Makefile:22: tewii-medium-11.bdf] Error 127
make: *** [Makefile:22: tewi2a-bold-11.bdf] Error 127
python2 is not supported by python3.5
make: *** [Makefile:22: tewihm-bold-11.bdf] Error 127
python2 is not supported by python3.5
make: *** [Makefile:22: tewii-bold-11.bdf] Error 127
```
