### ISSUE TITLE
Table for getting unicode values?

### ISSUE THREAD

**Issue by PaBLoX-CL** [lucy/tewi-font#9]
I'm trying in a 1080p screen, get some icons... I ran `glyphs`, and copy the content over another editor so I can be sure about the font, but the icon is minuscule :(. And therefore, I can't be sure how can I copy it. 

Maybe something like this could be useful?

https://github.com/phallus/fonts

Thanks for your font :)

**Comment by lucy** [comment]
Use gbdfed.

**Comment by PaBLoX-CL** [comment]
Thanks, it works really well. I also found `gucharmap` which also serves the purpose.
